<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-09-12T14:09:45 IST" name="Default suite" finished-at="2019-09-12T14:10:34 IST" duration-ms="48772">
    <groups>
    </groups>
    <test started-at="2019-09-12T14:09:45 IST" name="Default test" finished-at="2019-09-12T14:10:34 IST" duration-ms="48772">
      <class name="LINKEDIN.linkedin_DDT">
        <test-method is-config="true" signature="openBrowserToLogin(org.testng.ITestContext)[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64]" started-at="2019-09-12T14:09:45 IST" name="openBrowserToLogin" finished-at="2019-09-12T14:10:01 IST" duration-ms="15226" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@37df14d1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowserToLogin -->
        <test-method is-config="true" signature="startingTest(org.testng.ITestResult)[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64]" started-at="2019-09-12T14:10:01 IST" name="startingTest" finished-at="2019-09-12T14:10:01 IST" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=linkedin_DDT.execution()[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startingTest -->
        <test-method signature="execution()[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64]" started-at="2019-09-12T14:10:01 IST" name="execution" finished-at="2019-09-12T14:10:33 IST" duration-ms="32584" status="FAIL">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Execution  error -- ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Execution  error -- 
at com.linkedin.pages.searchJobApplyPage.clickonEasyApply(searchJobApplyPage.java:238)
at com.linkedin.pages.searchJobApplyPage.clickOnJoblink(searchJobApplyPage.java:169)
at LINKEDIN.linkedin_DDT.execution(linkedin_DDT.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- execution -->
        <test-method is-config="true" signature="conclution(org.testng.ITestResult)[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64]" started-at="2019-09-12T14:10:33 IST" name="conclution" finished-at="2019-09-12T14:10:34 IST" duration-ms="331" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=execution status=FAILURE method=linkedin_DDT.execution()[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclution -->
        <test-method is-config="true" signature="aaahhhh(org.testng.ITestContext)[pri:0, instance:LINKEDIN.linkedin_DDT@72c28d64]" started-at="2019-09-12T14:10:34 IST" name="aaahhhh" finished-at="2019-09-12T14:10:34 IST" duration-ms="578" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@37df14d1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aaahhhh -->
      </class> <!-- LINKEDIN.linkedin_DDT -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
